import { Instrument_Serif, Montserrat  } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: '400',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${instrumentSerif.className}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
